DROP TABLE SUBMITS purge;
DROP TABLE NPO_CUSTOMER purge;
DROP TABLE HOLDS purge;
DROP TABLE FIELD_CONTENT purge;
DROP TABLE CONTAINS purge;
DROP TABLE FIELD CASCADE CONSTRAINTS purge;
DROP TABLE DIGITIALFORM CASCADE CONSTRAINTS purge;
DROP TABLE NPO_ADMIN purge;